-- MySQL Script generated by MySQL Workbench
-- Fri Feb 15 14:07:09 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db-expertos
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db-expertos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db-expertos` DEFAULT CHARACTER SET utf8 ;
USE `db-expertos` ;

-- -----------------------------------------------------
-- Table `db-expertos`.`persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db-expertos`.`persona` (
  `idpersona` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  `correo` VARCHAR(45) NULL,
  PRIMARY KEY (`idpersona`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db-expertos`.`plan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db-expertos`.`plan` (
  `idplan` INT NOT NULL,
  `tipoPlan` VARCHAR(45) NULL,
  `descripcion` VARCHAR(45) NULL,
  `cantidadProyectos` INT NULL,
  PRIMARY KEY (`idplan`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db-expertos`.`carpeta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db-expertos`.`carpeta` (
  `idcarpeta` INT NOT NULL,
  `nombreCarpeta` VARCHAR(45) NULL,
  `fechaCreacion` DATE NULL,
  `idSubCarpeta` INT NOT NULL,
  PRIMARY KEY (`idcarpeta`),
  INDEX `fk_carpeta_carpeta1_idx` (`idSubCarpeta` ASC),
  CONSTRAINT `fk_carpeta_carpeta1`
    FOREIGN KEY (`idSubCarpeta`)
    REFERENCES `db-expertos`.`carpeta` (`idcarpeta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db-expertos`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db-expertos`.`usuario` (
  `idusuario` INT NOT NULL,
  `usuario` VARCHAR(45) NULL,
  `contrasena` VARCHAR(45) NULL,
  `idpersona` INT NOT NULL,
  `idplan` INT NOT NULL,
  PRIMARY KEY (`idusuario`, `idpersona`, `idplan`),
  INDEX `fk_usuario_persona1_idx` (`idpersona` ASC),
  INDEX `fk_usuario_plan1_idx` (`idplan` ASC),
  CONSTRAINT `fk_usuario_persona1`
    FOREIGN KEY (`idpersona`)
    REFERENCES `db-expertos`.`persona` (`idpersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_plan1`
    FOREIGN KEY (`idplan`)
    REFERENCES `db-expertos`.`plan` (`idplan`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `db-expertos`.`proyecto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db-expertos`.`proyecto` (
  `idproyecto` INT NOT NULL,
  `nombreProyecto` VARCHAR(45) NULL,
  `archivoHTML` VARCHAR(200) NULL,
  `archivoCSS` VARCHAR(200) NULL,
  `archivoJS` VARCHAR(200) NULL,
  `fechaCreacion` DATE NULL,
  `idcarpeta` INT NOT NULL,
  PRIMARY KEY (`idproyecto`, `idcarpeta`),
  INDEX `fk_proyecto_carpeta1_idx` (`idcarpeta` ASC),
  CONSTRAINT `fk_proyecto_carpeta1`
    FOREIGN KEY (`idcarpeta`)
    REFERENCES `db-expertos`.`carpeta` (`idcarpeta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db-expertos`.`plan_x_proyecto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db-expertos`.`plan_x_proyecto` (
  `idplan` INT NOT NULL,
  `idproyecto` INT NOT NULL,
  PRIMARY KEY (`idplan`, `idproyecto`),
  INDEX `fk_plan_has_proyecto_proyecto1_idx` (`idproyecto` ASC),
  INDEX `fk_plan_has_proyecto_plan1_idx` (`idplan` ASC),
  CONSTRAINT `fk_plan_has_proyecto_plan1`
    FOREIGN KEY (`idplan`)
    REFERENCES `db-expertos`.`plan` (`idplan`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_plan_has_proyecto_proyecto1`
    FOREIGN KEY (`idproyecto`)
    REFERENCES `db-expertos`.`proyecto` (`idproyecto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db-expertos`.`colaboradores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db-expertos`.`colaboradores` (
  `idcolaboradores` INT NOT NULL,
  `idusuario` INT NOT NULL,
  `idproyecto` INT NOT NULL,
  PRIMARY KEY (`idcolaboradores`, `idusuario`, `idproyecto`),
  INDEX `fk_colaboradores_usuario1_idx` (`idusuario` ASC),
  INDEX `fk_colaboradores_proyecto1_idx` (`idproyecto` ASC),
  CONSTRAINT `fk_colaboradores_usuario1`
    FOREIGN KEY (`idusuario`)
    REFERENCES `db-expertos`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_colaboradores_proyecto1`
    FOREIGN KEY (`idproyecto`)
    REFERENCES `db-expertos`.`proyecto` (`idproyecto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db-expertos`.`archivo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db-expertos`.`archivo` (
  `idarchivo` INT NOT NULL,
  `nombreArchivo` VARCHAR(45) NULL,
  `contenido` VARCHAR(500) NULL,
  `extensionArchivo` VARCHAR(45) NULL,
  `fechaCreacion` DATE NULL,
  `idcarpeta` INT NOT NULL,
  PRIMARY KEY (`idarchivo`, `idcarpeta`),
  INDEX `fk_archivo_carpeta1_idx` (`idcarpeta` ASC),
  CONSTRAINT `fk_archivo_carpeta1`
    FOREIGN KEY (`idcarpeta`)
    REFERENCES `db-expertos`.`carpeta` (`idcarpeta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db-expertos`.`estadoNotificacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db-expertos`.`estadoNotificacion` (
  `idestadoNotificacion` INT NOT NULL,
  `estadoNotificacion` VARCHAR(45) NULL,
  PRIMARY KEY (`idestadoNotificacion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db-expertos`.`notificacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db-expertos`.`notificacion` (
  `idnotificacion` INT NOT NULL,
  `fechaNotificacion` DATE NULL,
  `descripcion` VARCHAR(100) NULL,
  `idusuario` INT NOT NULL,
  `idestadoNotificacion` INT NOT NULL,
  PRIMARY KEY (`idnotificacion`, `idusuario`, `idestadoNotificacion`),
  INDEX `fk_notificacion_usuario1_idx` (`idusuario` ASC),
  INDEX `fk_notificacion_estadoNotificacion1_idx` (`idestadoNotificacion` ASC),
  CONSTRAINT `fk_notificacion_usuario1`
    FOREIGN KEY (`idusuario`)
    REFERENCES `db-expertos`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_notificacion_estadoNotificacion1`
    FOREIGN KEY (`idestadoNotificacion`)
    REFERENCES `db-expertos`.`estadoNotificacion` (`idestadoNotificacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db-expertos`.`pago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db-expertos`.`pago` (
  `idpago` INT NOT NULL,
  `fechaPago` DATE NULL,
  `numeroTarjeta` INT NULL,
  `nombreTarjeta` VARCHAR(45) NULL,
  `codigoCVV` INT(4) NULL,
  `idusuario` INT NOT NULL,
  `cantidadPago` VARCHAR(45) NULL,
  PRIMARY KEY (`idpago`, `idusuario`),
  INDEX `fk_pago_usuario1_idx` (`idusuario` ASC),
  CONSTRAINT `fk_pago_usuario1`
    FOREIGN KEY (`idusuario`)
    REFERENCES `db-expertos`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db-expertos`.`estadoSolicitud`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db-expertos`.`estadoSolicitud` (
  `idestadoSolicitud` INT NOT NULL,
  `estadoSolicitud` VARCHAR(45) NULL,
  PRIMARY KEY (`idestadoSolicitud`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db-expertos`.`solicitudColaboracion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db-expertos`.`solicitudColaboracion` (
  `idsolicitudColaboracion` INT NOT NULL,
  `fechaSolicitud` DATE NULL,
  `descripcion` VARCHAR(45) NULL,
  `idproyecto` INT NOT NULL,
  `idcolaboradores` INT NOT NULL,
  `idestadoSolicitud` INT NOT NULL,
  PRIMARY KEY (`idsolicitudColaboracion`, `idproyecto`, `idcolaboradores`, `idestadoSolicitud`),
  INDEX `fk_solicitudColaboracion_proyecto1_idx` (`idproyecto` ASC),
  INDEX `fk_solicitudColaboracion_colaboradores1_idx` (`idcolaboradores` ASC),
  INDEX `fk_solicitudColaboracion_estadoSolicitud1_idx` (`idestadoSolicitud` ASC),
  CONSTRAINT `fk_solicitudColaboracion_proyecto1`
    FOREIGN KEY (`idproyecto`)
    REFERENCES `db-expertos`.`proyecto` (`idproyecto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_solicitudColaboracion_colaboradores1`
    FOREIGN KEY (`idcolaboradores`)
    REFERENCES `db-expertos`.`colaboradores` (`idcolaboradores`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_solicitudColaboracion_estadoSolicitud1`
    FOREIGN KEY (`idestadoSolicitud`)
    REFERENCES `db-expertos`.`estadoSolicitud` (`idestadoSolicitud`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
